version: "3.9"
services:
  backend:
    image: ghcr.io/pixselve-school/tp1-wm:master
    depends_on:
      - db
      - rabbitmq
    environment:
      - DB_HOST=db
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=postgres
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - DEFAULT_USER_PASS=admin
      - DEFAULT_USER_EMAIL=admin@administration.fr
      - FRONTEND_URL=http://localhost/
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db-data:/var/lib/postgresql/data
  nginx:
    image: nginx:latest
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
  quarkus:
    image: ghcr.io/pixselve-school/quarkus-wm-project:master
    environment:
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - QUARKUS_MAILER_HOST=smtp
  rabbitmq:
    image: rabbitmq:3.11.3-management-alpine
    ports:
      - "15672:15672"
    volumes:
      - "./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins"
  smtp:
    image: soulteary/maildev
    ports:
      - "1080:1080"
  prometheus:
    image: prom/prometheus
    depends_on:
      - backend
      - quarkus
      - rabbitmq
    volumes:
      - prometheus-data:/prometheus
      - ./profiling/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - ./profiling/grafana-dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./profiling/grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./profiling/dashboards/:/var/lib/grafana/dashboards

  front:
    image: ghcr.io/pixselve-school/wm-projet:main

volumes:
    prometheus-data:


