version: "3.9"
services:
  backend:
    image: ghcr.io/pixselve-school/tp1-wm:master
    depends_on:
      - db
      - rabbitmq
    environment:
      - DB_HOST=db
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=postgres
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db-data:/var/lib/postgresql/data
  nginx:
    image: nginx:latest
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
  quarkus:
    image: ghcr.io/pixselve-school/quarkus-wm-project:master
    environment:
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - QUARKUS_MAILER_HOST=smtp
  rabbitmq:
    image: rabbitmq:3.11.3-management-alpine
    ports:
      - "15672:15672"
  smtp:
    image: soulteary/maildev
    ports:
      - "1080:1080"

