version: "3.9"
services:
  backend:
    build:
      context: ./backend/
      dockerfile: dev.Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
      - rabbitmq
    environment:
      - DB_HOST=db
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=postgres
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - DEFAULT_USER_PASS=admin
      - DEFAULT_USER_EMAIL=admin@administration.fr
      - FRONTEND_URL=http://localhost/
    volumes:
      - ./backend/src:/app/src
  front:
    build:
      context: ./frontend/
      dockerfile: dev.Dockerfile
    volumes:
      - ./frontend/src:/app/src
    ports:
      - "4200:4200"
  quarkus:
    image: ghcr.io/pixselve-school/quarkus-wm-project:master
    environment:
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - QUARKUS_MAILER_HOST=smtp
    ports:
      - "8080:8080"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db-data:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3.11.3-management-alpine
    volumes:
      - "./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins"
    ports:
      - "5672:5672"
      - "15672:15672"
  smtp:
    image: soulteary/maildev
    ports:
      - "1080:1080"
  prometheus:
    image: prom/prometheus
    depends_on:
      - backend
      - quarkus
      - rabbitmq
    volumes:
      - prometheus-data:/prometheus
      - ./profiling/prometheus.yml:/etc/prometheus/prometheus.yml
    profiles:
      - monitoring
  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - ./profiling/grafana-dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./profiling/grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./profiling/dashboards/:/var/lib/grafana/dashboards
    ports:
      - "3001:3000"
    profiles:
      - monitoring

volumes:
  prometheus-data:


