{
 "title": "Quarkus Overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Event Creation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Event Creation Request Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "application_countEventCreation_total",
     "legendFormat": "Event Creation Request Total"
    }
   ]
  },
  {
   "title": "Event Creation per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 1 },
   "targets": [
    {
     "expr": "round(increase(application_countEventCreation_total[1m]), 1)",
     "legendFormat": "Event Creation per minute"
    }
   ]
  },
  {
   "title": "Event Creation Request Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "application_org_acme_MainService_creationEventTime_mean_seconds",
     "legendFormat": "Event Creation Request Time"
    }
   ]
  },
  { "title": "Registration Confirmation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Registration Confirmation Request Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "application_countRegistrationConfirmation_total",
     "legendFormat": "Registration Confirmation Request Total"
    }
   ]
  },
  {
   "title": "Registration confirmation per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 10 },
   "targets": [
    {
     "expr": "round(increase(application_countRegistrationConfirmation_total[1m]), 1)",
     "legendFormat": "Registration confirmation per minute"
    }
   ]
  },
  {
   "title": "Registration Confirmation Request Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "application_org_acme_MainService_registrationConfirmationTime_mean_seconds",
     "legendFormat": "Event Creation Request Time"
    }
   ]
  }
 ]
}